import { City, Event, NewMember, Review, UserProfile } from './types'

export const cities: City[] = [
  {
    id: '1',
    name: '서울',
    province: '서울특별시',
    emoji: '🏙️',
    overall_score: 8.5,
    cost_per_month: '2.1~3M',
    internet_speed: 950,
    nomads_count: 524,
    cafe_rating: 4.7,
    work_score: 9.5,
    quality_score: 8.3,
    reviews_count: 245,
    description: '한국의 중심, 가장 많은 노마드가 활동하는 도시',
    gallery_images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=500',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=500',
      'https://images.unsplash.com/photo-1523482580672-f400141e6155?w=500',
    ],
    activities: [
      { id: 'a1', name: '경주시 불국사', category: 'culture', description: '유네스코 세계유산 불국사 방문', icon: '🏯' },
      { id: 'a2', name: '명동 쇼핑', category: 'shopping', description: '유명 쇼핑 거리에서 최신 유행 제품 구매', icon: '🛍️' },
      { id: 'a3', name: '한강 공원 자전거', category: 'activity', description: '한강공원에서 자전거 타기', icon: '🚴' },
      { id: 'a4', name: '한옥 마을 투어', category: 'culture', description: '북촌 한옥마을 전통 문화 체험', icon: '🏘️' },
    ],
    tips: [
      { id: 't1', title: '지하철 교통카드', description: 'T-money 카드로 지하철, 버스, 편의점 결제', category: 'transport', icon: '🚇' },
      { id: 't2', title: '밤 문화 활동', description: '서울은 밤 문화가 발달되어 있고, 카페와 바가 늦게까지 운영됨', category: 'culture', icon: '🌙' },
      { id: 't3', title: '편의점 음식', description: 'GS25, CU, 이마트24 등 24시간 편의점에서 저렴한 식사', category: 'food', icon: '🍜' },
    ],
    weather: { temperature: 15, condition: 'Partly Cloudy', icon: '⛅', humidity: 65 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
  {
    id: '2',
    name: '강릉',
    province: '강원도',
    emoji: '🏔️',
    overall_score: 8.3,
    cost_per_month: '1.2~1.8M',
    internet_speed: 200,
    nomads_count: 189,
    cafe_rating: 4.6,
    work_score: 7.8,
    quality_score: 8.9,
    reviews_count: 156,
    description: '바다와 산이 어우러진 평화로운 도시',
    gallery_images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500',
      'https://images.unsplash.com/photo-1511884642898-4c92249e20b6?w=500',
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500',
    ],
    activities: [
      { id: 'a1', name: '정동진 해돋이', category: 'nature', description: '해맞이열차를 타고 정동진에서 일출 관상', icon: '🌅' },
      { id: 'a2', name: '오죽헌 방문', category: 'culture', description: '신사임당의 생가 오죽헌에서 한국 전통 문화 체험', icon: '🎋' },
      { id: 'a3', name: '강릉 해변 산책', category: 'activity', description: '경포 해변에서 여유로운 산책', icon: '🏖️' },
      { id: 'a4', name: '커피거리 투어', category: 'food', description: '강릉의 유명한 커피거리에서 로컬 카페 방문', icon: '☕' },
    ],
    tips: [
      { id: 't1', title: '해맞이열차', description: '겨울 시즌에 운영되는 해맞이열차 예약 필수', category: 'transport', icon: '🚂' },
      { id: 't2', title: '현지 식재료', description: '강릉 오징어순대, 초당순두부 등 지역 맛있는 음식 추천', category: 'food', icon: '🦑' },
      { id: 't3', title: '계절별 활동', description: '여름 물놀이, 겨울 스키, 봄 벚꽃 등 계절마다 다른 매력', category: 'culture', icon: '🌸' },
    ],
    weather: { temperature: 12, condition: 'Rainy', icon: '🌧️', humidity: 78 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
  {
    id: '3',
    name: '전주',
    province: '전라북도',
    emoji: '🏯',
    overall_score: 8.1,
    cost_per_month: '1.4~2M',
    internet_speed: 250,
    nomads_count: 142,
    cafe_rating: 4.8,
    work_score: 7.5,
    quality_score: 8.7,
    reviews_count: 128,
    description: '문화와 전통이 살아있는 매력적인 도시',
    gallery_images: [
      'https://images.unsplash.com/photo-1583697162222-aebb256cb406?w=500',
      'https://images.unsplash.com/photo-1550355291-bbee04a92027?w=500',
      'https://images.unsplash.com/photo-1571898868541-f48e36766d5e?w=500',
    ],
    activities: [
      { id: 'a1', name: '한옥마을 탐방', category: 'culture', description: '전주 한옥마을에서 전통 건축 감상 및 사진촬영', icon: '📸' },
      { id: 'a2', name: '전주 비빔밥 체험', category: 'food', description: '전주 비빔밥 맛집투어 및 요리 클래스', icon: '🍚' },
      { id: 'a3', name: '오목대 야경', category: 'nature', description: '오목대에서 보는 전주 야경', icon: '🌃' },
      { id: 'a4', name: '경기전 방문', category: 'culture', description: '조선 왕실의 역사를 담은 경기전 관광', icon: '🏰' },
    ],
    tips: [
      { id: 't1', title: '한옥마을 투어', description: '가이드 투어로 더 깊이 있는 역사 학습', category: 'culture', icon: '👨‍🏫' },
      { id: 't2', title: '야경 명소', description: '저녁 시간대 오목대에서의 야경이 최고', category: 'culture', icon: '🌉' },
      { id: 't3', title: '전통 음식', description: '침채, 비빔밥, 콩나물국밥 등 전주 특산 음식 필수', category: 'food', icon: '🍜' },
    ],
    weather: { temperature: 18, condition: 'Clear', icon: '☀️', humidity: 55 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
  {
    id: '4',
    name: '부산',
    province: '부산광역시',
    emoji: '🌊',
    overall_score: 8.0,
    cost_per_month: '1.8~2.5M',
    internet_speed: 500,
    nomads_count: 267,
    cafe_rating: 4.5,
    work_score: 8.2,
    quality_score: 7.8,
    reviews_count: 184,
    description: '대한민국 제2의 도시, 활기찬 분위기',
    gallery_images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500',
      'https://images.unsplash.com/photo-1510344674702-092f90ee6b7b?w=500',
      'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=500',
    ],
    activities: [
      { id: 'a1', name: '해운대 해변', category: 'nature', description: '부산의 유명한 해변에서 해수욕 및 수상 스포츠', icon: '🏄' },
      { id: 'a2', name: '광안리 야경', category: 'nature', description: '광안대교의 야경과 해변에서의 로맨틱한 시간', icon: '🌃' },
      { id: 'a3', name: '감천문화마을', category: 'culture', description: '알록달록한 집들이 가득한 감천문화마을 탐방', icon: '🏘️' },
      { id: 'a4', name: '부산 해산물', category: 'food', description: '남포동 횟집거리에서 신선한 회 및 해산물 맛보기', icon: '🦐' },
    ],
    tips: [
      { id: 't1', title: '대중교통', description: '부산 1호선 등 발달된 지하철 네트워크', category: 'transport', icon: '🚇' },
      { id: 't2', title: '야식문화', description: '늦은 밤까지 영업하는 식당과 카페가 풍부', category: 'food', icon: '🌙' },
      { id: 't3', title: '여행 명소', description: '해운대, 광안리, 감천마을 등 관광지 밀집', category: 'culture', icon: '🗺️' },
    ],
    weather: { temperature: 17, condition: 'Sunny', icon: '☀️', humidity: 60 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
  {
    id: '5',
    name: '대구',
    province: '대구광역시',
    emoji: '🏢',
    overall_score: 7.8,
    cost_per_month: '1.2~1.7M',
    internet_speed: 300,
    nomads_count: 98,
    cafe_rating: 4.4,
    work_score: 7.2,
    quality_score: 7.6,
    reviews_count: 92,
    description: '저렴한 생활비와 친절한 지역민',
    gallery_images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500',
      'https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?w=500',
      'https://images.unsplash.com/photo-1571898868541-f48e36766d5e?w=500',
    ],
    activities: [
      { id: 'a1', name: '팔공산 트래킹', category: 'nature', description: '자연을 품은 팔공산에서의 하이킹 및 경치 감상', icon: '⛰️' },
      { id: 'a2', name: '대구 한약거리', category: 'culture', description: '동인동 약령시에서 한약 및 전통 의약품 구경', icon: '🌿' },
      { id: 'a3', name: '닝크 기차마을', category: 'activity', description: '지역 예술가의 작품이 가득한 아트 스페이스 방문', icon: '🚂' },
      { id: 'a4', name: '대구 음식 투어', category: 'food', description: '찜닭, 우육면 등 대구 대표 음식 맛보기', icon: '🍗' },
    ],
    tips: [
      { id: 't1', title: '저렴한 생활비', description: '서울보다 훨씬 저렴한 식비와 숙박비', category: 'accommodation', icon: '💰' },
      { id: 't2', title: '친절한 사람들', description: '지역민의 따뜻한 환영과 도움을 받을 수 있음', category: 'culture', icon: '👋' },
      { id: 't3', title: '음식 문화', description: '전통 한정식부터 현대 카페까지 다양한 음식 문화', category: 'food', icon: '🍽️' },
    ],
    weather: { temperature: 20, condition: 'Clear', icon: '☀️', humidity: 50 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
  {
    id: '6',
    name: '제주',
    province: '제주특별자치도',
    emoji: '🏝️',
    overall_score: 7.9,
    cost_per_month: '2.2~3M',
    internet_speed: 450,
    nomads_count: 201,
    cafe_rating: 4.7,
    work_score: 8.0,
    quality_score: 9.1,
    reviews_count: 167,
    description: '아름다운 자연과 함께하는 노마드 생활',
    gallery_images: [
      'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
      'https://images.unsplash.com/photo-1473496169865-658ba7c44d8a?w=500',
    ],
    activities: [
      { id: 'a1', name: '한라산 트래킹', category: 'nature', description: '제주도의 최고봉 한라산에서의 등산 및 자연 경험', icon: '⛰️' },
      { id: 'a2', name: '유명 해변 투어', category: 'activity', description: '협재 해변, 금모래 해변, 사주해변 등 제주의 아름다운 해변 방문', icon: '🏖️' },
      { id: 'a3', name: '제주 흑돼지 맛집', category: 'food', description: '제주의 명물 흑돼지 구워먹기 및 지역 음식 체험', icon: '🐷' },
      { id: 'a4', name: '오름 탐방', category: 'nature', description: '성산 일출봉, 용머리 해안 등 독특한 화산 지형 탐방', icon: '🌋' },
    ],
    tips: [
      { id: 't1', title: '계절별 날씨', description: '겨울에는 추우므로 따뜻한 옷 준비, 여름에는 햇빛 대비 필요', category: 'safety', icon: '🌤️' },
      { id: 't2', title: '교통 수단', description: '렌터카 이용 추천, 버스는 있지만 도시보다 시간이 많이 걸림', category: 'transport', icon: '🚗' },
      { id: 't3', title: '로컬 음식', description: '검은콩국수, 갈치구이, 옝니 등 제주만의 특별한 음식 체험', category: 'food', icon: '🍜' },
    ],
    weather: { temperature: 16, condition: 'Partly Cloudy', icon: '⛅', humidity: 72 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
  {
    id: '7',
    name: '광주',
    province: '광주광역시',
    emoji: '🏙️',
    overall_score: 7.6,
    cost_per_month: '1.1~1.6M',
    internet_speed: 280,
    nomads_count: 73,
    cafe_rating: 4.3,
    work_score: 7.0,
    quality_score: 8.2,
    reviews_count: 68,
    description: '예술의 도시, 창의적인 분위기',
    gallery_images: [
      'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=500',
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=500',
      'https://images.unsplash.com/photo-1578301978162-7aae4d755744?w=500',
    ],
    activities: [
      { id: 'a1', name: '광주 미술관', category: 'culture', description: '광주 국립미술관에서 한국 및 세계 미술작품 감상', icon: '🎨' },
      { id: 'a2', name: '양림동 예술거리', category: 'culture', description: '무장애 산책로와 갤러리, 카페가 있는 예술 지구 탐방', icon: '🖼️' },
      { id: 'a3', name: '동명동 음식문화거리', category: 'food', description: '광주의 향로 요리, 중국집, 카페 등 다양한 음식 체험', icon: '🥡' },
      { id: 'a4', name: '광주 비엔날레 정원', category: 'activity', description: '아트 설치미술과 정원을 즐기는 산책 코스', icon: '🌸' },
    ],
    tips: [
      { id: 't1', title: '예술 문화', description: '광주 비엔날레, 미술관 전시 등 문화 행사가 자주 열림', category: 'culture', icon: '🎭' },
      { id: 't2', title: '저렴한 물가', description: '타 지역 대비 매우 저렴한 식비와 숙박비', category: 'accommodation', icon: '💰' },
      { id: 't3', title: '로컬 음식 추천', description: '광주식 나주곰탕, 광주의 향로, 수제 떡 등 지역 음식 필수', category: 'food', icon: '🍲' },
    ],
    weather: { temperature: 19, condition: 'Clear', icon: '☀️', humidity: 58 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
  {
    id: '8',
    name: '대전',
    province: '대전광역시',
    emoji: '🌆',
    overall_score: 7.5,
    cost_per_month: '1.3~1.8M',
    internet_speed: 350,
    nomads_count: 85,
    cafe_rating: 4.2,
    work_score: 7.3,
    quality_score: 7.9,
    reviews_count: 75,
    description: '과학과 기술의 도시, 미래 지향적',
    gallery_images: [
      'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=500',
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    activities: [
      { id: 'a1', name: '국립중앙과학관', category: 'culture', description: '최첨단 과학기술을 경험할 수 있는 과학관 방문', icon: '🔬' },
      { id: 'a2', name: '엑스포 과학공원', category: 'activity', description: '대전 엑스포 기념 공원에서의 산책 및 과학 전시', icon: '🎡' },
      { id: 'a3', name: '대전 음식 투어', category: 'food', description: '계룡산 닭계탕, 대전식 우동 등 지역 음식 체험', icon: '🍗' },
      { id: 'a4', name: '유성온천', category: 'nature', description: '유성호와 온천에서의 힐링 및 스파 체험', icon: '♨️' },
    ],
    tips: [
      { id: 't1', title: '과학 문화', description: '카이스트, 국립중앙과학관 등 과학 관련 시설이 풍부', category: 'culture', icon: '🧪' },
      { id: 't2', title: '교통 편의성', description: '대전역, 중부 고속도로 등 교통 교통 중심지로 이동 편리', category: 'transport', icon: '🚄' },
      { id: 't3', title: '온천과 휴식', description: '유성온천에서의 온천욕 및 스파는 업무 스트레스 해소에 최고', category: 'accommodation', icon: '🧘' },
    ],
    weather: { temperature: 18, condition: 'Clear', icon: '☀️', humidity: 62 },
    currency: { code: 'KRW', exchange_rate: 1200 },
  },
]

export const reviews: Review[] = [
  // Seoul reviews
  {
    id: 'r1',
    user_id: 'u1',
    city_id: '1',
    username: '김노마드',
    title: '인터넷이 빠르고 카페 문화가 좋아요',
    content: '서울의 카페 문화는 정말 훌륭합니다. 어디서나 빠른 인터넷을 이용할 수 있고, 노마드를 위한 시설이 잘 갖춰져 있습니다.',
    rating: 5,
    created_at: '2025-01-15',
  },
  {
    id: 'r2',
    user_id: 'u2',
    city_id: '1',
    username: 'Alice_Seoul',
    title: '물가가 비싼 편이지만 가치있어요',
    content: '생활비가 다른 도시보다 높지만, 직업 기회와 네트워킹이 많아서 충분히 보상됩니다. 노마드 커뮤니티도 활발합니다.',
    rating: 4,
    created_at: '2025-01-10',
  },
  {
    id: 'r3',
    user_id: 'u3',
    city_id: '1',
    username: 'Mike_Work',
    title: '일하기 최고의 환경',
    content: '업무 환경이 정말 좋습니다. 스터디 카페, 코워킹 스페이스, 비즈니스 라운지 등 옵션이 많아서 원하는 분위기를 찾을 수 있습니다.',
    rating: 5,
    created_at: '2025-01-08',
  },
  {
    id: 'r4',
    user_id: 'u4',
    city_id: '1',
    username: '박여행자',
    title: '너무 바쁘고 스트레스 받아요',
    content: '확실히 일할 수 있는 환경은 좋지만, 도시가 너무 빨리 돌아가서 힐링하기 어렵습니다. 조용한 곳을 찾는다면 다른 도시가 낫습니다.',
    rating: 3,
    created_at: '2025-01-05',
  },

  // Gangneung reviews
  {
    id: 'r5',
    user_id: 'u5',
    city_id: '2',
    username: '강원사랑',
    title: '자연과 함께하는 노마드 생활',
    content: '산과 바다의 경치가 정말 아름답습니다. 생활비도 저렴하고, 적당한 속도의 인터넷이 있어서 충분히 일할 수 있습니다.',
    rating: 4,
    created_at: '2025-01-12',
  },
  {
    id: 'r6',
    user_id: 'u6',
    city_id: '2',
    username: 'Sarah_Nature',
    title: '평화로움을 찾는다면 여기로',
    content: '서울에서의 바쁜 생활을 떠나 강릉에 왔는데, 정말 마음이 편해졌습니다. 로컬 카페도 좋고 사람들이 친절합니다.',
    rating: 5,
    created_at: '2025-01-03',
  },
  {
    id: 'r7',
    user_id: 'u7',
    city_id: '2',
    username: '박개발자',
    title: '인터넷 속도가 아쉬워요',
    content: '전반적으로 좋은 도시이지만, 인터넷 속도가 서울보다 많이 느립니다. 대용량 파일 다운로드나 화상 통화가 불편할 수 있습니다.',
    rating: 3,
    created_at: '2024-12-28',
  },

  // Jeonju reviews
  {
    id: 'r8',
    user_id: 'u8',
    city_id: '3',
    username: '전주매력',
    title: '문화와 전통이 살아있는 도시',
    content: '한옥마을이 정말 아름답고, 전통 음식도 맛있습니다. 카페 평점도 높아서 일하기 좋은 환경입니다.',
    rating: 5,
    created_at: '2025-01-14',
  },
  {
    id: 'r9',
    user_id: 'u9',
    city_id: '3',
    username: 'Cultural_Tom',
    title: '감성적인 도시에서의 작업',
    content: '관광지가 많아서 주말에 즐길 게 많습니다. 생활비도 합리적이고 카페 문화가 발달해 있어서 좋습니다.',
    rating: 4,
    created_at: '2025-01-09',
  },
  {
    id: 'r10',
    user_id: 'u10',
    city_id: '3',
    username: '김문화',
    title: '조용하고 좋아요',
    content: '서울보다 훨씬 조용하고 물가도 저렴합니다. 한 달 정도 머물면서 여유있게 일할 수 있습니다.',
    rating: 4,
    created_at: '2025-01-01',
  },

  // Busan reviews
  {
    id: 'r11',
    user_id: 'u11',
    city_id: '4',
    username: '부산활기',
    title: '해변과 함께하는 활기찬 도시',
    content: '해수욕장이 가까워서 일하다가 스트레스 받으면 바다를 보며 쉴 수 있습니다. 밤 문화도 활발합니다.',
    rating: 4,
    created_at: '2025-01-13',
  },
  {
    id: 'r12',
    user_id: 'u12',
    city_id: '4',
    username: 'Beach_Digital',
    title: '야외 활동과 일의 균형',
    content: '서울보다 느긋하고, 생활비도 저렴합니다. 인터넷도 충분히 빨라서 불편함이 없습니다.',
    rating: 4,
    created_at: '2025-01-07',
  },
  {
    id: 'r13',
    user_id: 'u13',
    city_id: '4',
    username: '이바다',
    title: '노마드 커뮤니티가 활발해요',
    content: '부산에 노마드들이 많이 모여 있어서 네트워킹 기회가 많습니다. 정기 밋업도 자주 있습니다.',
    rating: 5,
    created_at: '2024-12-30',
  },

  // Daegu reviews
  {
    id: 'r14',
    user_id: 'u14',
    city_id: '5',
    username: '대구경제',
    title: '저렴한 생활비가 매력이에요',
    content: '한국에서 가장 저렴한 생활비입니다. 월 1.2M정도로 충분하고, 음식도 맛있고 저렴합니다.',
    rating: 4,
    created_at: '2025-01-11',
  },
  {
    id: 'r15',
    user_id: 'u15',
    city_id: '5',
    username: 'Budget_Nomad',
    title: '작은 도시의 매력',
    content: '서울에 비해 훨씬 조용하고 여유있습니다. 인터넷도 충분하고, 지역민들이 매우 친절합니다.',
    rating: 4,
    created_at: '2025-01-02',
  },
  {
    id: 'r16',
    user_id: 'u16',
    city_id: '5',
    username: '최저비용',
    title: '가성비 최고의 도시',
    content: '이 정도 가격에 이 정도 시설을 찾기 어렵습니다. 단기 스테이에 최고입니다.',
    rating: 5,
    created_at: '2024-12-25',
  },

  // Jeju reviews
  {
    id: 'r17',
    user_id: 'u17',
    city_id: '6',
    username: '제주천국',
    title: '천국 같은 섬에서의 일',
    content: '자연 경치가 정말 아름답고, 카페도 예쁘고 질이 좋습니다. 인터넷도 빨라서 신경쓸 게 없습니다.',
    rating: 5,
    created_at: '2025-01-16',
  },
  {
    id: 'r18',
    user_id: 'u18',
    city_id: '6',
    username: 'Island_Life',
    title: '일과 여유의 완벽한 조화',
    content: '아침엔 일하고 오후엔 해변에서 쉴 수 있습니다. 생활비가 좀 비싸지만 그만한 가치가 있습니다.',
    rating: 5,
    created_at: '2025-01-06',
  },
  {
    id: 'r19',
    user_id: 'u19',
    city_id: '6',
    username: '정섬',
    title: '삶의 질이 좋은 도시',
    content: '제주의 삶의 질 점수가 높은 이유를 알 수 있습니다. 스트레스 없이 일할 수 있는 최고의 환경입니다.',
    rating: 5,
    created_at: '2024-12-20',
  },

  // Gwangju reviews
  {
    id: 'r20',
    user_id: 'u20',
    city_id: '7',
    username: '광주예술',
    title: '창의적인 분위기가 있어요',
    content: '예술의 도시답게 창의적인 에너지가 있습니다. 카페들도 독특하고 아티스트들도 많습니다.',
    rating: 4,
    created_at: '2025-01-04',
  },
  {
    id: 'r21',
    user_id: 'u21',
    city_id: '7',
    username: 'Creative_Worker',
    title: '저렴하고 창의적인 도시',
    content: '생활비가 저렴하면서도 문화 시설이 많습니다. 디자이너나 크리에이터들에게 좋은 도시입니다.',
    rating: 4,
    created_at: '2024-12-31',
  },
  {
    id: 'r22',
    user_id: 'u22',
    city_id: '7',
    username: '박광주',
    title: '숨은 보석 같은 도시',
    content: '많은 사람들이 모르지만, 정말 좋은 도시입니다. 조용하고, 저렴하고, 친절합니다.',
    rating: 4,
    created_at: '2024-12-15',
  },

  // Daejeon reviews
  {
    id: 'r23',
    user_id: 'u23',
    city_id: '8',
    username: '대전기술',
    title: '과학과 기술의 도시',
    content: '미래 지향적인 도시 분위기입니다. 인터넷도 빠르고 IT 산업이 발달해 있습니다.',
    rating: 4,
    created_at: '2025-01-17',
  },
  {
    id: 'r24',
    user_id: 'u24',
    city_id: '8',
    username: 'Tech_Nomad',
    title: '개발자 친화적인 도시',
    content: '기술 기업들이 많고, IT 커뮤니티도 활발합니다. 생활비도 합리적입니다.',
    rating: 4,
    created_at: '2025-01-01',
  },
  {
    id: 'r25',
    user_id: 'u25',
    city_id: '8',
    username: '이미래',
    title: '균형잡힌 도시',
    content: '일하기도 좋고, 생활비도 저렴하고, 사람들도 친절합니다. 장기 스테이에 추천합니다.',
    rating: 4,
    created_at: '2024-12-22',
  },
]

export const events: Event[] = [
  // Seoul events
  {
    id: 'e1',
    city_id: '1',
    title: '서울 노마드 네트워킹 이벤트',
    description: '서울의 디지털 노마드들이 모여 경험과 팁을 공유하는 네트워킹 행사입니다.',
    category: 'networking',
    date: '2025-02-10',
    time: '18:00',
    location: '강남역 카페홀',
    creator_id: 'u1',
    creator_name: '김노마드',
    participant_count: 24,
    created_at: '2025-01-20',
  },
  {
    id: 'e2',
    city_id: '1',
    title: 'Next.js 워크숍',
    description: '최신 Next.js 기술 트렌드를 배우고 실습하는 워크숍입니다.',
    category: 'workshop',
    date: '2025-02-15',
    time: '14:00',
    location: '서울시 강남구 테크홀',
    creator_id: 'u2',
    creator_name: 'Alice_Seoul',
    participant_count: 18,
    created_at: '2025-01-19',
  },
  {
    id: 'e3',
    city_id: '1',
    title: '서울 디지털노마드 사교모임',
    description: '매주 금요일 저녁, 함께 시간을 보내며 네트워크를 확장하세요.',
    category: 'social',
    date: '2025-02-14',
    time: '19:00',
    location: '홍대 펍 거리',
    creator_id: 'u3',
    creator_name: 'Mike_Work',
    participant_count: 32,
    created_at: '2025-01-18',
  },

  // Gangneung events
  {
    id: 'e4',
    city_id: '2',
    title: '강릉 해변 요가',
    description: '아침 해가 뜨며 진행되는 해변 요가 클래스입니다.',
    category: 'sports',
    date: '2025-02-12',
    time: '07:00',
    location: '강릉 정동진 해변',
    creator_id: 'u5',
    creator_name: '강원사랑',
    participant_count: 15,
    created_at: '2025-01-17',
  },
  {
    id: 'e5',
    city_id: '2',
    title: '강릉 문화예술 투어',
    description: '경포대와 오죽헌 등 강릉의 문화유산을 함께 탐방합니다.',
    category: 'culture',
    date: '2025-02-16',
    time: '10:00',
    location: '경포대 입구',
    creator_id: 'u6',
    creator_name: 'Sarah_Nature',
    participant_count: 12,
    created_at: '2025-01-16',
  },

  // Jeonju events
  {
    id: 'e6',
    city_id: '3',
    title: '전주 한옥마을 가이드 투어',
    description: '전통 한옥마을을 전문가와 함께 돌아보는 투어입니다.',
    category: 'culture',
    date: '2025-02-13',
    time: '11:00',
    location: '전주 한옥마을 입구',
    creator_id: 'u8',
    creator_name: '전주매력',
    participant_count: 28,
    created_at: '2025-01-15',
  },
  {
    id: 'e7',
    city_id: '3',
    title: '전주 비빔밥 요리 클래스',
    description: '전주 비빔밥을 직접 만들며 배우는 요리 클래스입니다.',
    category: 'workshop',
    date: '2025-02-18',
    time: '15:00',
    location: '전주 문화센터',
    creator_id: 'u9',
    creator_name: 'Cultural_Tom',
    participant_count: 10,
    created_at: '2025-01-14',
  },

  // Busan events
  {
    id: 'e8',
    city_id: '4',
    title: '부산 해운대 네트워킹 밋업',
    description: '부산 노마드 커뮤니티 정기 모임입니다.',
    category: 'networking',
    date: '2025-02-11',
    time: '18:30',
    location: '해운대 카페',
    creator_id: 'u11',
    creator_name: '부산활기',
    participant_count: 20,
    created_at: '2025-01-13',
  },
  {
    id: 'e9',
    city_id: '4',
    title: '부산 서핑 레슨',
    description: '초보자를 위한 서핑 레슨입니다. 안전 장비 제공.',
    category: 'sports',
    date: '2025-02-17',
    time: '08:00',
    location: '광안리 해변',
    creator_id: 'u12',
    creator_name: 'Beach_Digital',
    participant_count: 8,
    created_at: '2025-01-12',
  },

  // Daegu events
  {
    id: 'e10',
    city_id: '5',
    title: '대구 디지털마케팅 세미나',
    description: '최신 디지털마케팅 트렌드를 배우는 세미나입니다.',
    category: 'workshop',
    date: '2025-02-14',
    time: '19:00',
    location: '대구 비즈니스센터',
    creator_id: 'u14',
    creator_name: '대구경제',
    participant_count: 25,
    created_at: '2025-01-11',
  },

  // Jeju events
  {
    id: 'e11',
    city_id: '6',
    title: '제주 한 달 노마드 체험',
    description: '제주에서 한 달을 함께 일하고 놀며 경험하는 프로그램입니다.',
    category: 'social',
    date: '2025-02-19',
    time: '09:00',
    location: '제주시 중앙로',
    creator_id: 'u17',
    creator_name: '제주천국',
    participant_count: 16,
    created_at: '2025-01-10',
  },
  {
    id: 'e12',
    city_id: '6',
    title: '제주 감귤 딸기 체험',
    description: '제주의 신선한 과일을 직접 수확하고 맛보는 체험입니다.',
    category: 'culture',
    date: '2025-02-20',
    time: '13:00',
    location: '제주 남부지역 농장',
    creator_id: 'u18',
    creator_name: 'Island_Life',
    participant_count: 14,
    created_at: '2025-01-09',
  },

  // Gwangju events
  {
    id: 'e13',
    city_id: '7',
    title: '광주 예술 갤러리 투어',
    description: '광주의 유명 미술관과 갤러리를 돌아보는 투어입니다.',
    category: 'culture',
    date: '2025-02-15',
    time: '14:00',
    location: '광주 문화예술거리',
    creator_id: 'u20',
    creator_name: '광주예술',
    participant_count: 11,
    created_at: '2025-01-08',
  },

  // Daejeon events
  {
    id: 'e14',
    city_id: '8',
    title: '대전 과학 테크 세미나',
    description: '최신 과학기술 트렌드를 배우는 세미나입니다.',
    category: 'workshop',
    date: '2025-02-21',
    time: '16:00',
    location: '대전 과학센터',
    creator_id: 'u23',
    creator_name: '대전기술',
    participant_count: 22,
    created_at: '2025-01-07',
  },
]

// Legacy support
export const meetups = events

export const newMembers: NewMember[] = [
  {
    id: '1',
    username: 'valdenicio',
    joined_date: '2025-01-20',
  },
  {
    id: '2',
    username: 'davidfox',
    joined_date: '2025-01-19',
  },
  {
    id: '3',
    username: 'linlin',
    joined_date: '2025-01-18',
  },
]

export const stats = {
  total_users: 38211,
  total_cities: 47,
  total_items_rated: 1200,
  total_reviews: 2450,
  monthly_meetups: 23,
  monthly_new_members: 244,
}

export const regions = [
  { label: '서울/경기', value: 'seoul' },
  { label: '강원도', value: 'gangwon' },
  { label: '전라도', value: 'jeonlla' },
  { label: '경상도', value: 'gyeongsan' },
  { label: '충청도', value: 'chungcheong' },
  { label: '제주도', value: 'jeju' },
]

export const sortOptions = [
  { label: '🌟 종합점수순', value: 'overall' },
  { label: '💰 저렴한순', value: 'cheap' },
  { label: '📶 빠른순', value: 'fast' },
  { label: '👥 활발한순', value: 'active' },
  { label: '🎉 삶의질순', value: 'quality' },
  { label: '👍 리뷰 많은순', value: 'reviews' },
]

export const currentUser: UserProfile = {
  id: 'current_user_123',
  email: 'nomad@korea.com',
  name: '로그인 사용자',
  bio: '한국에서 디지털 노마드 생활을 즐기는 중입니다.',
  avatar_url: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nomad123',
  created_at: '2024-10-15',
}
