import { City, Meetup, NewMember } from './types'

export const cities: City[] = [
  {
    id: '1',
    name: '서울',
    province: '서울특별시',
    emoji: '🏙️',
    overall_score: 8.5,
    cost_per_month: '2.1~3M',
    internet_speed: 950,
    nomads_count: 524,
    cafe_rating: 4.7,
    work_score: 9.5,
    quality_score: 8.3,
    reviews_count: 245,
    description: '한국의 중심, 가장 많은 노마드가 활동하는 도시',
    image_url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800&h=600&fit=crop',
  },
  {
    id: '2',
    name: '강릉',
    province: '강원도',
    emoji: '🏔️',
    overall_score: 8.3,
    cost_per_month: '1.2~1.8M',
    internet_speed: 200,
    nomads_count: 189,
    cafe_rating: 4.6,
    work_score: 7.8,
    quality_score: 8.9,
    reviews_count: 156,
    description: '바다와 산이 어우러진 평화로운 도시',
    image_url: 'https://picsum.photos/seed/Kangneung/800/600',
  },
  {
    id: '3',
    name: '전주',
    province: '전라북도',
    emoji: '🏯',
    overall_score: 8.1,
    cost_per_month: '1.4~2M',
    internet_speed: 250,
    nomads_count: 142,
    cafe_rating: 4.8,
    work_score: 7.5,
    quality_score: 8.7,
    reviews_count: 128,
    description: '문화와 전통이 살아있는 매력적인 도시',
    image_url: 'https://picsum.photos/800/600?random=3',
  },
  {
    id: '4',
    name: '부산',
    province: '부산광역시',
    emoji: '🌊',
    overall_score: 8.0,
    cost_per_month: '1.8~2.5M',
    internet_speed: 500,
    nomads_count: 267,
    cafe_rating: 4.5,
    work_score: 8.2,
    quality_score: 7.8,
    reviews_count: 184,
    description: '대한민국 제2의 도시, 활기찬 분위기',
    image_url: 'https://picsum.photos/800/600?random=4',
  },
  {
    id: '5',
    name: '대구',
    province: '대구광역시',
    emoji: '🏢',
    overall_score: 7.8,
    cost_per_month: '1.2~1.7M',
    internet_speed: 300,
    nomads_count: 98,
    cafe_rating: 4.4,
    work_score: 7.2,
    quality_score: 7.6,
    reviews_count: 92,
    description: '저렴한 생활비와 친절한 지역민',
    image_url: 'https://picsum.photos/seed/Daegu/800/600',
  },
  {
    id: '6',
    name: '제주',
    province: '제주특별자치도',
    emoji: '🏝️',
    overall_score: 7.9,
    cost_per_month: '2.2~3M',
    internet_speed: 450,
    nomads_count: 201,
    cafe_rating: 4.7,
    work_score: 8.0,
    quality_score: 9.1,
    reviews_count: 167,
    description: '아름다운 자연과 함께하는 노마드 생활',
    image_url: 'https://picsum.photos/seed/Jeju/800/600',
  },
  {
    id: '7',
    name: '광주',
    province: '광주광역시',
    emoji: '🏙️',
    overall_score: 7.6,
    cost_per_month: '1.1~1.6M',
    internet_speed: 280,
    nomads_count: 73,
    cafe_rating: 4.3,
    work_score: 7.0,
    quality_score: 8.2,
    reviews_count: 68,
    description: '예술의 도시, 창의적인 분위기',
    image_url: 'https://picsum.photos/seed/Gwangju/800/600',
  },
  {
    id: '8',
    name: '대전',
    province: '대전광역시',
    emoji: '🌆',
    overall_score: 7.5,
    cost_per_month: '1.3~1.8M',
    internet_speed: 350,
    nomads_count: 85,
    cafe_rating: 4.2,
    work_score: 7.3,
    quality_score: 7.9,
    reviews_count: 75,
    description: '과학과 기술의 도시, 미래 지향적',
    image_url: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=600&fit=crop',
  },
]

export const meetups: Meetup[] = [
  {
    id: '1',
    city_id: '1',
    title: '강남 카페 밋업',
    date: 'Mon 27th',
    location: '강남역 인근',
  },
  {
    id: '2',
    city_id: '4',
    title: '해운대 노마드 모임',
    date: 'Sat 25th',
    location: '해운대 해수욕장',
  },
  {
    id: '3',
    city_id: '6',
    title: '제주 월간 밋업',
    date: 'Fri 24th',
    location: '제주시 중앙로',
  },
]

export const newMembers: NewMember[] = [
  {
    id: '1',
    username: 'valdenicio',
    joined_date: '2025-01-20',
  },
  {
    id: '2',
    username: 'davidfox',
    joined_date: '2025-01-19',
  },
  {
    id: '3',
    username: 'linlin',
    joined_date: '2025-01-18',
  },
]

export const stats = {
  total_users: 38211,
  total_cities: 47,
  total_items_rated: 1200,
  total_reviews: 2450,
  monthly_meetups: 23,
  monthly_new_members: 244,
}

export const regions = [
  { label: '서울/경기', value: 'seoul' },
  { label: '강원도', value: 'gangwon' },
  { label: '전라도', value: 'jeonlla' },
  { label: '경상도', value: 'gyeongsan' },
  { label: '충청도', value: 'chungcheong' },
  { label: '제주도', value: 'jeju' },
]

export const sortOptions = [
  { label: '🌟 종합점수순', value: 'overall' },
  { label: '💰 저렴한순', value: 'cheap' },
  { label: '📶 빠른순', value: 'fast' },
  { label: '👥 활발한순', value: 'active' },
  { label: '🎉 삶의질순', value: 'quality' },
  { label: '👍 리뷰 많은순', value: 'reviews' },
]
